INSERT INTO USERS (NAME, PHONE_NUMBER, EMAIL_ADDRESS) VALUES ("", "", "");
INSERT INTO USERS (NAME, PHONE_NUMBER, EMAIL_ADDRESS) VALUES ("", "", "");
INSERT INTO USERS (NAME, PHONE_NUMBER, EMAIL_ADDRESS) VALUES ("", "", "");
