# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: St. A Communications
email: andrew@pythias.io
description: > # this means to ignore newlines until "baseurl:"
    Saint A digital communications platform
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://stacomms.site" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Other custom settings
form_one_url:  "http://goo.gl/forms/4D1gQgZIXS"  # TL
form_two_url:  "http://goo.gl/forms/GkPkCbjG5x"  # Admin
responses_url:  ""
